all:
  hosts:
    production:
      ansible_host: 162.222.34.121
      ansible_user: ubuntu
      ansible_ssh_private_key_file: "{{ lookup('env', 'SSH_KEY_PATH') | default('/tmp/deploy-key', true) }}"
  vars:
    dd_env: production
    cp_memory: 8G
    cp_cpus: 8
    agent_memory: 64G
    agent_cpus: 16
    agent_node_size: llm
